apiVersion: v1
kind: Secret
metadata:
  name: tech-challange-testing-auth-demo
  namespace: tech-challenge-testing
type: Opaque
stringData:
  DB_HOST: "tech-challange-testing-ext.demo"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "" # get the value from kubedb secret tech-challange-testing-auth and create a user for the app
  DB_NAME: "lanchonete"