version: '3'
services:
  msvc-orders:
    build: ./msvc-orders
    ports:
      - 8080:8080
    environment:
      DB_URI: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      REDIS_URI: redis://:@kvs:6379/0
      ORDER_URI: http://msvc-orders:8080
      PAYMENT_URI: http://msvc-payments:8081
      PRODUCTION_URI: http://msvc-production:8082
    depends_on:
      - db
      - redis
    networks:
      - msvc-network

  msvc-payments:
    build: ./msvc-payments
    ports:
      - 8081:8080
    environment:
      DB_URI: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      REDIS_URI: redis://:@kvs:6379/0
      ORDER_URI: http://msvc-orders:8080
      PAYMENT_URI: http://msvc-payments:8081
      PRODUCTION_URI: http://msvc-production:8082
    depends_on:
      - db
      - redis
    networks:
      - msvc-network

  msvc-production:
    build: ./msvc-production
    ports:
      - 8082:8080
    environment:
      DB_URI: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      REDIS_URI: redis://:@kvs:6379/0
      ORDER_URI: http://msvc-orders:8080
      PAYMENT_URI: http://msvc-payments:8081
      PRODUCTION_URI: http://msvc-production:8082
    depends_on:
      - db
      - redis
    networks:
      - msvc-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - msvc-network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - msvc-network

volumes:
  postgres_data:
  redis_data:

networks:
  msvc-network: