# .github/workflows/ci.yml

name: Build and Push

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: "${{ github.repository }}"
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions/setup-earthly@v1
      with:
        version: latest
    - uses: actions/checkout@v4
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Earthly version
      run: earthly --version
    - name: Debug Registry
      run: echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" && echo "$IMAGE_NAME"
    - name: Run build
      run: earthly --push +all
      working-directory: devsecops/cicd/build
  trivy:
    uses: ./.github/workflows/trivy.yml
    needs: build-and-push
  linter:
    uses: ./.github/workflows/golangci-lint.yml
    needs: build-and-push
  autotest:
    uses: ./.github/workflows/autotest.yml
    needs: build-and-push
  delivery-fase-2:
    uses: ./.github/workflows/delivery-fase-2.yml
    needs: build-and-push
  
  # snyk:
  #   uses: ./.github/workflows/snyk-security.yml
  #   needs: build-and-push